kind: pipeline
type: docker
name: default

steps:
- name: ZeroNorth Security
  image: docker:dind
  user: root
  commands:
  - docker run --help
  - docker --version
  - docker pull zeronorth/integration:latest
  - docker run -e SCENARIO=owaspv5 -e POLICY_NAME=${DRONE_REPO_NAME}:owaspv5 -e TARGET_NAME=${DRONE_REPO_NAME} -e FAIL_ON_HIGH_SEVERITY=0 -e STAGE=build -e WAIT_FOR_COMPLETION=false -v DRONE_REPO_BRANCH:/code -v DRONE_REPO_BRANCH:/results -v /var/run/docker.sock:/var/run/docker.sock -e SONAR_JAVA_LIBRARY_DIR=\".\" -e SONAR_JAVA_BINARY_DIR=\".\" -e CYBRIC_API_KEY=$ZN_API_KEY zeronorth/integration:latest python cybric.py
  environment:
    ZN_API_KEY:
      from_secret: ZN_API_KEY
      
      
- name: Build with Gradle
  image: gradle:jdk10
  user: root
  commands:
  - chmod +x gradle/
  - ls -la
  - ./gradlew build
  
  


