kind: pipeline
type: docker
name: Security 

steps:
- name: Download ZeroNorth Security CLI 
  image: gradle:jdk10
  commands:
  - curl -O https://support.zeronorth.io/hc/en-us/article_attachments/1500009379522/zn_cli_ubuntu2004_20210409
  - ls -la
  - pwd

- name: ZeroNorth Scans
  image: gradle:jdk10
  commands:
  - java -jar VeracodeJavaAPI.jar -vid $VERACODE_API_ID -vkey $VERACODE_API_SECRET -action UploadAndScan -appname ${DRONE_REPO_NAME} -createprofile false -filepath target/verademo.war -version Commit ${DRONE_COMMIT_REF}
  environment:
      SCENARIO: owaspv5
      ZN_API_KEY:
        from_secret: ZN_API_KEY
        
---
kind: pipeline
type: docker
name: Build

steps:
- name: Build with Gradle
  image: gradle:jdk10
  user: root
  commands:
  - chmod +x gradle/
  - ls -la
  - ./gradlew build

depends_on:
- Security



  
